# BINARY STEP FUNCTION

In [2]:
def binary_step(x):
    if x<0:
        return 0
    else:return 1

In [3]:
binary_step(12)

1

In [4]:
binary_step(-6)

0

In [5]:
binary_step(6)

1

In [7]:
binary_step(-8)

0

# LINEAR FUNCTION

In [9]:
def linear_function(x):
    return 3*x

In [10]:
linear_function(10)

30

In [11]:
linear_function(-9)

-27

In [12]:
linear_function(4)

12

In [13]:
linear_function(6)

18

# SIGMOID FUNCTION

In [14]:
import numpy as np

In [15]:
 def sigmoid_function(x):
        z=(1/(1+np.exp(-x)))
        return z

In [16]:
sigmoid_function(4)

0.9820137900379085

In [17]:
sigmoid_function(-4)

0.01798620996209156

In [18]:
sigmoid_function(2)

0.8807970779778823

In [19]:
sigmoid_function(-2)

0.11920292202211755

# TANH FUNCTION

In [21]:
 def tanh_function(x):
        z=(2/(1+np.exp(-2*x)))
        return z

In [22]:
tanh_function(6)

1.9999877116507956

In [23]:
tanh_function(-6)

1.2288349204429436e-05

In [24]:
tanh_function(8)

1.9999997749296758

In [25]:
tanh_function(-8)

2.2507032411019e-07

# RELU FUNCTION

In [27]:
def relu_function(x):
    if x<0:
        return 0 
    else:
        return x

In [28]:
relu_function(5)

5

In [29]:
relu_function(-5)

0

In [30]:
relu_function(8)

8

In [31]:
relu_function(-8)

0

# LEAKY RELU FUNCTION

In [32]:
def leaky_relu_function(x):
    if x<0:
        return 0.01*x 
    else:
        return x

In [33]:
leaky_relu_function(4)

4

In [34]:
leaky_relu_function(7)

7

In [35]:
leaky_relu_function(6)

6

In [36]:
leaky_relu_function(3)

3

# ELU FUNCTION

In [37]:
def elu_function(x,a):
    if x<0:
        return a*(np.exp(x)-1)
    else:
        return x

In [38]:
elu_function(1,2)

1

In [39]:
elu_function(5,8)

5

In [40]:
elu_function(-7,8)

-7.992704944275564

In [41]:
elu_function(-6,4)

-3.9900849912933345

# SWISH FUNCTION 

In [42]:
def swish_function(x):
    return x/(1-np.exp(-x))

In [43]:
swish_function(-45)

1.2881333612472272e-18

In [44]:
swish_function(23)

23.00000000236023

In [47]:
swish_function(-15)

4.588536211171261e-06

In [48]:
swish_function(8)

8.00268460160673

# SOFTMAX FUNCTION

In [49]:
def softmax_function(x):
    z=np.exp(x)
    z_=z/z.sum()
    return z_

In [51]:
softmax_function([2.0,1.0,0.1])

array([0.65900114, 0.24243297, 0.09856589])

In [52]:
softmax_function([4.0,5.0,0.9])

array([0.26572204, 0.72230739, 0.01197057])

In [53]:
softmax_function([14.0,8.0,0.23])

array([9.97526335e-01, 2.47262058e-03, 1.04397321e-06])

In [56]:
softmax_function([4.0,5.0,0.4])

array([0.26697953, 0.7257256 , 0.00729487])